### ISSUE TITLE
Remove hpxml requirement for `number_of_residential_units`

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-example-geojson-project#192]
`number_of_residential_units` is required in the geojson file, possibly starting in HPXML v1.7.0. The check for this field doesn't need to exist as this information should be, and is, contained within the HPXML file itself. AFAIK there isn't any problem removing this check from the code.

**Comment by joseph-robertson** [comment]
Hi @vtnate. Are you able to point explicitly to the check you're referring to in this issue?

**Comment by vtnate** [comment]
Hmmm, good question. No, I can't find it now. That seems like a good indicator that this is a stale issue! I'll close and if it's a problem in the future we can sort it out then.
