### ISSUE TITLE
Error when the cloned repository path is too long

### ISSUE THREAD

**Issue by rawadelkontar** [urbanopt/urbanopt-example-geojson-project#43]
Cloning the urbanopt-example-geojson-project repo in the Cdrive is a workaround to this issue. 

When the repo is cloned into a nested directory the file path is too long causing the following Error : 
Could not find openstudio-model-articulation-0.1.1 in any of the sources. 

- Configuring git to allow long path names in git " git config --global core.longpaths true" doesn't seem to solve the issue !

**Comment by kflemin** [comment]
OpenStudio 3.0 will add a better error message to explain the situation (instead of "could not find ... in any of the sources).    Other than that there is nothing we can do about long path names on windows.

**Comment by vtnate** [comment]
"Fixed" by better error messages in OSv3.0
